# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W2DV9t2-80QZerKzan5og11Y8OA4FBwM

# **CSSM502 Assignment 2**

**Task 1**
"""

import pandas as pd

# Upload Gapminder dataset
url = "https://raw.githubusercontent.com/resbaz/r-novice-gapminder-files/master/data/gapminder-FiveYearData.csv"
df = pd.read_csv(url)

df.info()
df.head()

"""**Task 3**"""

df.isnull().sum()

df = df.rename(columns={
    "pop": "Population",
    "lifeExp": "Life_Expectancy",
    "gdpPercap": "GDP_per_Capita"
})

df.head()

"""**Task 4**"""

df.info()
df.head()
df.tail()

df["country"].nunique()

df["country"].unique()

df_2002 = df[df["year"] == 2002]
df_2002.head()

"""**Task 5**"""

africa_df = df[df["continent"] == "Africa"]
africa_df.head()

africa_filtered = africa_df[africa_df["Population"] >= 1_000_000]
africa_filtered.head()

africa_filtered["country"].nunique()

"""**Task 6**"""

sorted_df = df.sort_values(by="Life_Expectancy", ascending=True)
sorted_df.head()

def categorize_population(pop):
    if pop < 5_000_000:
        return "Low"
    elif pop < 20_000_000:
        return "Medium"
    else:
        return "High"

df["Population_Category"] = df["Population"].apply(categorize_population)
df.head()

"""**Task** **7**"""

df.groupby("continent")["GDP_per_Capita"].mean()

year = 2002
highest_lifeExp_2002 = df[df["year"] == year].sort_values(
    by="Life_Expectancy",
    ascending=False
).head(1)

highest_lifeExp_2002

"""**Task 8**"""

import matplotlib.pyplot as plt

country = "Japan"

country_df = df[df["country"] == country]

plt.figure(figsize=(10,5))
plt.plot(country_df["year"], country_df["Life_Expectancy"], marker="o")
plt.title(f"Life Expectancy Over Time: {country}")
plt.xlabel("Year")
plt.ylabel("Life Expectancy")
plt.grid(True)
plt.show()