# -*- coding: utf-8 -*-
"""CSSM502_Hw5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WjrXcY9FPF23iYfJFg0JR9je6acDWGYt

# **Assignment 5**
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install geopandas libpysal esda spreg

import zipfile, os

base = "/content/drive/MyDrive/CSSM502/Assignment 5/Dataset"

with zipfile.ZipFile(os.path.join(base, "nhgis0001_shape.zip"), 'r') as z:
    z.extractall(os.path.join(base, "shape"))

with zipfile.ZipFile(os.path.join(base, "nhgis0001_csv.zip"), 'r') as z:
    z.extractall(os.path.join(base, "data"))

import geopandas as gpd

shape_dir = os.path.join(base, "shape")

# NHGIS zip yapısı derin olduğu için otomatik shp buluyoruz
shp_path = None
for root, dirs, files in os.walk(shape_dir):
    for file in files:
        if file.endswith(".shp"):
            shp_path = os.path.join(root, file)

counties = gpd.read_file(shp_path)
counties.head()

import pandas as pd

data_dir = os.path.join(base, "data")

csv_path = None
for root, dirs, files in os.walk(data_dir):
    for file in files:
        if file.endswith(".csv"):
            csv_path = os.path.join(root, file)

income = pd.read_csv(csv_path)
income.head()

# ALPXM colons
[col for col in income.columns if col.startswith("ALPXM")][:10]

income_sub = income[["GISJOIN", "ALPXM001"]].copy()
income_sub.rename(columns={"ALPXM001": "median_income"}, inplace=True)

income_sub.head()

merged = counties.merge(income_sub, on="GISJOIN")
merged.head()

merged["median_income"].isna().sum()

merged.plot(
    column="median_income",
    cmap="viridis",
    legend=True,
    figsize=(10,6)
)

from libpysal.weights import Queen

# Spatial weights (Queen contiguity)
w = Queen.from_dataframe(merged)

# Satır standardizasyonu
w.transform = 'R'

w

from esda.moran import Moran

moran = Moran(merged["median_income"], w)
moran.I, moran.p_sim

# Moran’s I is positive and statistically significant (I = 0.195, p < 0.01),
# indicating that median household income is spatially clustered across US counties.
# Counties with similar income levels tend to be located near each other.

import numpy as np

# dependent variable
y = merged["median_income"].values.reshape(-1, 1)

# independent variable (log area for stability)
X = np.log(merged["ALAND"].values).reshape(-1, 1)

from spreg import ML_Lag

lag_model = ML_Lag(
    y=y,
    x=X,
    w=w,
    name_y="Median Income",
    name_x=["Log Land Area"]
)

print(lag_model.summary)