# -*- coding: utf-8 -*-
"""CSSM502_Hw4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SG4tALW2SqF2Cx7MHenMBOuNZam4GVJ0

# **Assignment 4**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
import statsmodels.api as sm
import statsmodels.formula.api as smf

plt.style.use("seaborn-v0_8")

from google.colab import drive
drive.mount('/content/drive')

file_path = "/content/drive/MyDrive/CSSM502/Assignment 4/Dataset/GSS2022.dta"

import pandas as pd

gss = pd.read_stata(file_path)
gss.head()

gss.shape

gss.dtypes.head(20)

gss.info()

gss.select_dtypes(include=['int', 'float']).columns

gss['age'].head(10)

gss['age'].dtype

gss['age'].cat.categories[:10]

gss['age'] = gss['age'].replace('89 or older', pd.NA)
gss['age'] = pd.to_numeric(gss['age'])

gss['educ'].head(10)
gss['educ'].dtype
gss['educ'].cat.categories

gss['educ'] = gss['educ'].cat.add_categories([0])

gss['educ'] = gss['educ'].mask(gss['educ'] == 'no formal schooling', 0)

gss['educ'] = pd.to_numeric(gss['educ'])

gss['educ'].describe()

gss['realinc'].head(10)

gss['realinc'].dtype

gss['realinc'].cat.categories[:15]

gss['realinc'] = pd.to_numeric(gss['realinc'], errors='coerce')

gss['realinc'].describe()

analysis_df = gss[['age', 'educ', 'realinc', 'sex']].dropna()
analysis_df.shape

analysis_df[['age', 'educ', 'realinc']].describe()

analysis_df[['age', 'educ', 'realinc']].median()

analysis_df[['age', 'educ', 'realinc']].std()

import seaborn as sns
import matplotlib.pyplot as plt

sns.histplot(analysis_df['educ'], bins=20)
plt.title("Distribution of Years of Education")
plt.show()

sns.histplot(analysis_df['realinc'], bins=30)
plt.title("Distribution of Real Income")
plt.show()

analysis_df['sex'].value_counts(dropna=False)

analysis_df.groupby('sex')['educ'].count()

from scipy import stats

male_educ = analysis_df[analysis_df['sex'] == 'male']['educ']
female_educ = analysis_df[analysis_df['sex'] == 'female']['educ']

stats.ttest_ind(male_educ, female_educ, equal_var=False)

"""p-value = 0.836 > 0.05 so there is no statistically significant difference in years of education between men and women in the sample."""

analysis_df[['educ', 'age', 'realinc']].corr()

import seaborn as sns
import matplotlib.pyplot as plt

sns.scatterplot(x='educ', y='realinc', data=analysis_df)
plt.title("Education and Income")
plt.show()

analysis_df[['educ', 'age', 'realinc']].corr()

"""Education shows a moderate positive correlation with income, while age exhibits almost no linear relationship with income."""

import statsmodels.formula.api as smf

ols_model = smf.ols("realinc ~ educ + age", data=analysis_df).fit()
ols_model.summary()

"""Education has a positive and statistically significant effect on income.
One additional year of education is associated with approximately $5,100 higher annual income, holding age constant.
"""

import seaborn as sns
import matplotlib.pyplot as plt

sns.scatterplot(x=ols_model.fittedvalues, y=ols_model.resid)
plt.axhline(0, color='red')
plt.title("Residuals vs Fitted Values")
plt.xlabel("Fitted values")
plt.ylabel("Residuals")
plt.show()

sns.histplot(ols_model.resid, kde=True)
plt.title("Distribution of Residuals")
plt.show()

"""The main variables are education, age, and income. Before the analysis, the data were cleaned and prepared. The category “89 or older” in the age was removed because it does not represent an exact value. Education was measured in years of schooling. And there is also option that no formal schooling. So no formal schooling were coded as zero years. Income was converted to real income values for numerical analysis.

Descriptive statistics show that;
- education varies across respondents
- Most people have between 12 and 16 years of education
- Income is not evenly distributed
- Many respondents have low or middle income, while a small number have very high income

A t-test was used to compare education levels between male and female. It is important to use "male" and "female" becasue first think that likely do is coding man and woman as a 0 and 1. The results show no statistically significant difference. On average, men and women have similar years of education.

Correlation analysis shows a positive relationship between education and income. Higher education is usually linked to higher income. Age shows almost no linear relationship with income. An OLS regression was then estimated. The results show that education has a strong and statistically significant effect on income. One additional year of education is associated with about $5,100 higher income, holding age constant. Age is not a significant predictor once education is included. The model explains a limited part of income differences, which is expected. Diagnostic checks show that residuals are centered around zero, but variance increases for higher income levels. Residuals are not perfectly normal. The results can be considered reliable.
"""