# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/171WWxpPHkhtINCBuJusotfnlNW0VMyrS

# **Assignment 3**

## **Task 1**

I initially attempted to scrape data from BBC News and IMDb. However, both websites use strong bot protection, and since I was working on Google Colab, many pages were either blocked, incomplete, or returned empty HTML.
For this reason, I switched to TMDBs openly accessible web API. I still used the requests library to send HTTP GET calls to a web endpoint and extract the returned content in JSON format.

## **Task 2**
"""

!pip install parsel

!pip install requests parsel pandas

"""## **Task 3**"""

import requests
import pandas as pd

API_KEY = "fc74a62fa66dc14e73cc9cd41ad5a473"
movies = []

# 500 pages = 10.000 film
for page in range(1, 501):
    url = f"https://api.themoviedb.org/3/movie/popular?api_key={API_KEY}&language=en-US&page={page}"
    print("Fetching page:", page)

    r = requests.get(url)
    data = r.json()

    results = data.get("results", [])

    for film in results:
        movies.append({
            "title": film.get("title"),
            "overview": film.get("overview"),
            "release_date": film.get("release_date"),
            "vote_average": film.get("vote_average"),
            "vote_count": film.get("vote_count"),
            "popularity": film.get("popularity"),
            "original_language": film.get("original_language"),
            "movie_id": film.get("id")
        })

"""## **Task 4**"""

df = pd.DataFrame(movies)

df.drop_duplicates(inplace=True)

# Clean release date
df["release_date"] = pd.to_datetime(df["release_date"], errors="coerce")

# Fill missing text fields
df["overview"] = df["overview"].fillna("No description available")

df.reset_index(drop=True, inplace=True)
df.head()

"""## **Task 5**"""

df.to_csv("tmdb_10k_movies.csv", index=False)
df

"""## **Advanced Cleaning & Visualization**"""

df.describe(include="all")

df.describe(include="all")

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
df["vote_average"].plot(kind="hist", bins=30)
plt.title("Distribution of Movie Ratings")
plt.xlabel("Rating")
plt.ylabel("Count")
plt.show()

plt.figure(figsize=(8,5))
df["popularity"].plot(kind="hist", bins=40)
plt.title("Popularity Distribution")
plt.xlabel("Popularity")
plt.ylabel("Count")
plt.show()

df["year"] = df["release_date"].dt.year

df["year"].value_counts().sort_index().plot(kind="line", figsize=(10,5))
plt.title("Number of Movies by Year")
plt.xlabel("Year")
plt.ylabel("Movie Count")
plt.show()

from google.colab import drive
drive.mount('/content/drive')

!cp "/content/tmdb_10k_movies.csv" /content/drive/MyDrive/